### PR TITLE
Colons in date values being incorrectly escaped

### PR DESCRIPTION
**Pull request by nkezhaya**
Hi! I fixed a critical bug that prevents DateMath from parsing dates properly, because the colons in a date get escaped with _t.

Example:

created_at:[1976-03-06T23:59:59.999Z TO *] gets escaped to:

(created_at_t:[1976-03-06T23_t:59_t:59.999Z TO *]), which causes an error.

Now, it will properly escape:

(created_at_t:[1976-03-06T23:59:59.999Z TO *])

### CODE REVIEW

**Comment by nz** [comment]
Thanks for this, Nick! Your changes look good, and I know aas's test suite is a little stale, but I'd be remiss if I didn't ask for a unit test as well. Think you could take a stab at that?

Also, shouldn't date fields have the `_d` suffix? Perhaps you've stumbled across a bigger bug than we suspected here…

**Comment by nkezhaya** [comment]
Don't worry about the `_t` vs. `_d` issue. It looks like the appended `_t` gets replaced by `_d` later. Whew!

I think I can go ahead and slap together a unit test for this.

**Comment by nz** [comment]
Re `_t` vs `_d`: That makes sense, thanks for double checking on that. Can you tell I'm a bit out of date with acts_as_solr's internals? :)

**Comment by nz** [comment]
Applied (finally!). Updated release coming soon with another contributed patch.

**Pull request merged**
